SELECT * FROM FRECUENTA
INNER JOIN GUSTA ON FRECUENTA.PERSONA = GUSTA.PERSONA
INNER JOIN SIRVE ON GUSTA.CERVEZA = SIRVE.CERVEZA AND FRECUENTA.BAR = SIRVE.BAR;

SELECT * FROM GUSTA;
SELECT * FROM FRECUENTA;
SELECT * FROM SIRVE;

SELECT * FROM FRECUENTA, SIRVE, GUSTA
WHERE FRECUENTA.PERSONA = GUSTA.PERSONA AND SIRVE.BAR = FRECUENTA.BAR AND SIRVE.CERVEZA <> GUSTA.CERVEZA;

SELECT FRECUENTA.PERSONA FROM FRECUENTA WHERE PERSONA NOT IN (
	SELECT DISTINCT FRECUENTA.PERSONA FROM FRECUENTA, SIRVE, GUSTA
	WHERE FRECUENTA.PERSONA = GUSTA.PERSONA AND SIRVE.BAR = FRECUENTA.BAR AND SIRVE.CERVEZA <> GUSTA.CERVEZA
);

DOUBLE NOT EXISTS ANIDADO

GROUP Y CONDICIONES AL GRUPO
SQL (CLAUDIA)
